<table class="table table-hover purchase_products">
    <thead>
    <th class="col-lg-1 text-center">Product ID</th>
    <th class="col-lg-2 text-center">Product Name</th>    
    <th class="col-lg-1 text-center">Product SKU</th>
    <th class="col-lg-1 text-center">Product Unit Price</th>
    <th class="col-lg-1 text-center">Product Quantity</th>
    <th class="col-lg-1 text-center">Product Status</th>
    <th class="col-lg-1 text-center">Actions</th>
    </thead>
    <tbody>
<!--        <tr>
            <td class="text-center"><input type="text" id="supplier_id" class="form-control filter" onkeyup="SearchList(this)"/></td>
            <td class="text-center"><input type="text" id="supplier_name" class="form-control filter" onkeyup="SearchList(this)"/></td>
            <td class="text-center"><input type="text" id="supplier_email" class="form-control filter" onkeyup="SearchList(this)"/></td>
            <td class="text-center"><input type="text" id="supplier_phone" class="form-control filter" onkeyup="SearchList(this)"/></td>
            <td class="text-center"><input type="text" id="supplier_address" class="form-control filter" onkeyup="SearchList(this)"/></td>
            <td class="text-center">
                <select id="is_active" class="form-control filter" onchange="SearchList(this)" style="margin:0">
                    <option value="" selected disabled></option>
                    <option value="1">Enabled</option>
                    <option value="0">Disabled</option>
                </select>
            </td>
            <td></td>
        </tr>-->
<?php if(isset($products) and $products):?>
        <?php foreach($products as $product):?>
        <tr class="data">
            <td class="text-center"><?php echo $product['product_id'];?></td>
            <td class="text-center"><?php echo $product['product_name'];?></td>
            <td class="text-center"><?php echo $product['product_sku'];?></td>
            <td class="text-center"><?php echo $product['product_unit_price'];?></td>
            <td class="text-center"><?php echo $product['product_quantity'];?></td>
            <td class="text-center"><?php echo convertStatusIdToText($product['product_status']);?></td>
            <td class="text-center"><a href="<?php echo ADMIN_URL.'purchaseproducts/edit/'.$product['product_id']?>">Edit</a></td>
        </tr>
        <?php endforeach;?>
        <?php else:?>
        <tr class="data">
            <td colspan="7" class="text-center">No data found</td>
        </tr>
<?php endif; ?>
    </tbody>
</table>