<div class="row">
    <div class="col-lg-12 text-center">
        <div class="page-header">
            <h3>Daily Stock Count</h3>
        </div>
    </div>
</div>
<form method='post' action='<?php echo ADMIN_URL.'stock/dailycountpost'?>'>
    <input type='hidden' name='date' value='<?php echo date('Y-m-d');?>'/>
    <div class="stock-count">
<div class='row'>
    <div class='col-lg-2 col-lg-offset-1'>
        <p><?php echo date('F d, Y');?></p>
    </div>
</div>
    <div class="row">
        <div class="col-lg-10 col-lg-offset-1">
   <?php foreach($categories as $category):?>
    <ul>
    <?php $products = getModel('purchaseproduct')->getCategoryProducts($category['category_id']);?>
    <?php if($products):?>
    <li>
        <h4><?php echo $category['name'];?></h4>
        <div class='table-responsive'>
            <table class="table table-hover table-bordered">
                <thead>
                <th class='col-lg-1 text-center'>Item Code</th>
                <th class='col-lg-2 text-center'>Item Name</th>
                <th class='col-lg-1 text-center'>Item Quantity</th>
                <th class='col-lg-1 text-center'>Actual Quantity</th>
                </thead>
                <tbody>
    <?php foreach($products as $product):?>
                    <tr>
                        <td class='text-center'><?php echo $product['product_id'];?></td>
                        <td class='text-center'><?php echo $product['product_name'];?><input type="hidden" name="product_name[<?php echo $product['product_id']?>]" value="<?php echo $product['product_name']?>"/></td>
                        <?php $quantity = getModel('stock')->getTotalStock($product['product_id']);?>
                        <?php if(!$quantity):?>
                        <td class='text-center' class='text-center'>0<input type="hidden" name="calculated_quantity[<?php echo $product['product_id']?>]" value="0"/></td>
                        <?php else:?>
                        <td class='text-center'><?php echo $quantity['total_quantity'].' '.$quantity['unit_symbol']?>
                            <input type="hidden" name="calculated_quantity[<?php echo $product['product_id']?>]" value="<?php echo $quantity['total_quantity']?>"/>
                            <input type="hidden" name="unit[<?php echo $product['product_id']?>]" value="<?php echo $quantity['weight_unit_id']?>"/>
                        </td>
                        <?php endif;?>
                        <td class='text-center'><input type='text' name="daily_stock[<?php echo $product['product_id']?>]" style="margin: 0;" value="<?php echo isset($daily_stock[$product['product_id']])?$daily_stock[$product['product_id']]:null;?>"></td>
                    </tr>
    <?php endforeach;?>
                </tbody>
            </table>
        </div>
    </li>
    <?php endif;?>
</ul>
    <?php endforeach;?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-1 col-lg-offset-5">
                <input type="submit" class="btn btn-primary" style="width:100%" value="Save"/>
        </div>
        <div class="col-lg-1">
        <a href="javascript:void(0)" class="btn btn-info" style="width:100%" onclick="Print()" >Print</a>
        </div>

    </div>
    </div>
</form>
<script>
    function Print()
    {
//        w=window.open();
//w.document.write($('.stock-count').html());
//w.print();
//w.close();
        window.print();
    }
</script>