<div class="row">
    <div class="col-lg-12 text-center">
        <div class="page-header">
            <h3>Daily Stock Count</h3>
        </div>
    </div>
</div>
<form method='post' action='<?php echo ADMIN_URL.'stock/dailycountpost'?>'>
    <input type='hidden' name='date' value='<?php echo date('Y-m-d');?>'/>
<div class='row'>
    <div class='col-lg-2'>
        <p><?php echo date('F d, Y');?></p>
    </div>
</div>
</form>