<form method="post" action="<?php echo ADMIN_URL.'purchaseorders/addpost'?>">
	<table>
		<thead>
			<th>Product Name</th>
			<th>Product Unit Price</th>
			<th>Product Quantity</th>
			<th>Total Price</th>
		</thead>
		<tbody>
			<tr>
				<td>
					<select name="product[product_id][]">
						<option value="3">Feed</option>
						<option value="4">Hay</option>
					</select>
				</td>
				<td>
					<input type="number" name="product[unit_price][]" value="20" readonly class="unit_price"/>
				</td>
				<td>
					<input type="number" name="product[quantity][]" onkeyup = "calculateTotalPrice(this)" class="quantity"/>
				</td>
				<td>
					<input type="number" name = "product[total_price][]" class="total_price" onchange="updateUnitPrice(this)"/>
				</td>
			</tr>
		</tbody>
	</table>
			<input type="button" value="+" class="add-new-row" onclick="addNewRow()"/>

	<input type="submit" value="Save"/>
</form>
<script type="text/javascript">
function addNewRow()
{
	var html = $('table tbody tr').html();
	$('table tbody').append('<tr>'+html+'</tr>');

}

function calculateTotalPrice(quantity)
{
	var q = $(quantity).val();
	var u = $(quantity).parent().parent().find('.unit_price').val();
	var t = q * u;
	$(quantity).parent().parent().find('.total_price').val(t);
}

function updateUnitPrice(total_price)
{
	var t = $(total_price).val();
	var q = $(total_price).parent().parent().find('.quantity').val();
	var u = t/q;
	$(total_price).parent().parent().find('.unit_price').val(u);

}
</script>