<div class='table-responsive'>
    <table class="table table-hover table-bordered">
        <thead>
        <th class='col-lg-1 text-center'>Item Code</th>
        <th class='col-lg-2 text-center'>Item Name</th>
        <th class='col-lg-1 text-center'>Quantity</th>
        </thead>
        <tbody>
            <?php foreach ($products as $product): ?>
                <tr>
                    <td class='text-center'><?php echo $product['product_id']; ?></td>
                    <td class='text-center'><?php echo $product['product_name']; ?></td>
                    <?php $quantity = getModel('stock')->getTotalStock($product['product_id']); ?>
                    <?php if (!$quantity['total_quantity']): ?>
                        <td class='text-center'>0</td>
                    <?php else: ?>
                        <td class='text-center'><?php echo $quantity['total_quantity'] . ' ' . $quantity['unit_symbol'] ?></td>
                    <?php endif; ?>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>