<div class="panel panel-default">
    <div class="panel-heading text-center">
        <h3 class="panel-title">Edit Category</h3>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <div class="well">
                    <form method="post" action="<?php echo ADMIN_URL . 'purchasecategories/editpost' ?>">
                        <input type="hidden" value="<?php echo $category['category_id'] ?>" name="category_id"/>
                        <fieldset>
                            <div class="row">
                                <div class="col-lg-12">
                                    <label for="category_name">Category Name</label>
                                    <input type="text" name="category_name" class="form-control required" value="<?php echo $category['name'] ?>"/>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-12">
                                    <label for="category_sku">Category SKU</label>
                                    <input type="text" name="category_sku" class="form-control required" value="<?php echo $category['category_sku'] ?>"/>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-12">
                                    <label for="category_desc">Category Description</label>
                                    <textarea name="category_desc" class="form-control" value=""><?php echo $category['category_desc'] ?></textarea>
                                </div>
                            </div>
                            <?php if (isset($p_categories) and $p_categories): ?>
                                <div class="row">
                                    <div class="col-lg-12">
                                        <label for="parent">Parent Category</label>
                                        <select name="parent" class="form-control" style="margin:0">
                                            <option value="" <?php echo ($category['parent'] == 0 or $category['parent'] == 'NULL') ? 'selected' : null ?> disabled>NULL</option>
                                            <?php foreach ($p_categories as $cat): ?>
                                                <option value="<?php echo $cat['category_id'] ?>" <?php echo (($category['parent']) == $cat['category_id']) ? 'selected' : null ?>><?php echo $cat['name'] ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>
                            <?php endif; ?>
                            <div class="row">
                                <div class="col-lg-12">
                                    <label for="is_active">Is Active</label>
                                    <select name="is_active" class="form-control" style="margin:0">
                                        <option value="0" <?php echo ($category['is_active'] == 0) ? 'selected' : null ?>>No</option>
                                        <option value="1" <?php echo ($category['is_active'] == 1) ? 'selected' : null ?>>Yes</option>
                                    </select>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-12 text-right">
                                    <input type="submit" class="btn btn-primary" value="Save Category"/>
                                </div>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
