<?php AdminSession::showSuccessMessages(); ?>
<?php AdminSession::showSuccessMessages(); ?>
<div class="row">
    <div class="col-lg-12 text-center">
        <div class="page-header">
            <h3>Purchase Categories</h3>
        </div>
    </div>
</div>

<?php if (isset($categories)): ?>
    <div class="row">
        <div class="col-lg-2">
            <div class="panel panel-default">
                <div class="panel-heading text-center">
                    <h3 class="panel-title">Categories</h3>
                </div>
                <div class="panel-body">
                    <div class="row" id="new-button" style="display:none">
                        <div class="col-lg-6 col-lg-offset-3">
                            <a href="#" class="btn btn-block btn-primary add-new-category" onclick="LoadNewForm()">New Category</a>
                        </div>
                    </div>
                    <ul>
                        <li><a onclick="GetSubCategories(this, '<?php echo $categories['category_id'] ?>')" href="javascript:void(0)" class="load_sub_category" id="<?php echo $categories['category_id'] ?>"><i class="glyphicon glyphicon-plus"></i></a><a href="javascript:void(0)" onclick="LoadData(<?php echo $categories['category_id'] ?>)"><?php echo $categories['name']; ?></a>

                            <div class="sub_categories"></div>
                        </li>

                    </ul>
                </div>
            </div>
        </div>
        <div class="col-lg-8">
            <div class="form">
            </div>
        </div>
    </div>
<?php endif; ?>
<script>
    function GetSubCategories(icon, id)
    {
        $.ajax({
            url: '<?php echo ADMIN_URL . 'purchasecategories/getSubCategories/' ?>' + id,
            success: function (response) {
                console.log($(icon));
                $(icon).parent().find('.sub_categories').first().html(response);
            }
        });
    }

    function LoadData(id)
    {
        //alert(id);
        $('#new-button').show();
        $('.form').load('<?php echo ADMIN_URL . 'purchasecategories/editajax/' ?>' + id);
    }

    $(document).ready(function () {
        LoadNewForm();
    });

    function LoadNewForm()
    {
        $('.form').load('<?php echo ADMIN_URL . 'purchasecategories/add' ?>');
    }
</script>