<?php AdminSession::showSuccessMessages();?>
<?php AdminSession::showSuccessMessages();?>
<div class="row">
    <div class="col-lg-12 text-center">
        <div class="page-header">
            <h3>Purchase Categories</h3>
        </div>
    </div>
</div>

<?php if(isset($categories)):?>
<div class="row">
<div class="col-lg-4">
<ul>
    <li><a onclick="GetSubCategories(this,'<?php echo $categories['category_id']?>')" href="javascript:void(0)" class="load_sub_category" id="<?php echo $categories['category_id']?>"><i class="glyphicon glyphicon-plus"></i></a><a href="javascript:void(0)" onclick="LoadData(<?php echo $categories['category_id']?>)"><?php echo $categories['name'];?></a></li>
    <div class="sub_categories"></div>
</ul>
</div>
<div class="col-lg-8">
<div class="form">
</div>
</div>
</div>
<?php endif;?>
<script>
function GetSubCategories(icon,id)
{
    $.ajax({
        url:'<?php echo ADMIN_URL.'purchasecategories/getSubCategories/'?>'+id,
        success:function(response){
            console.log($(icon));
            $(icon).parent().parent().find('.sub_categories').first().html(response);
        }
    });
}

function LoadData(id)
{
    alert(id);
    $('.form').load('<?php echo ADMIN_URL.'purchasecategories/editajax/'?>'+id);    
}

$(document).ready(function(){
    $('.form').load('<?php echo ADMIN_URL.'purchasecategories/add'?>');
});
</script>