<?php if(isset($products) and $products):?>
	<?php
		$product_array = array();
		foreach($products as $product)
		{
			$product_array[$product['product_id']] = $product['unit_price'];
		}
	?>
	<script type="text/javascript">
		var products = <?php echo json_encode($product_array);?>;
		console.log(products);
	</script>
<form method="post" action="<?php echo ADMIN_URL.'purchaseorders/addpost'?>">
	<table class="table table-hover table-condensed">
		<thead>
			<th>Product Name</th>
			<th>Product Unit Price</th>
			<th>Product Quantity</th>
			<th>Total Price</th>
		</thead>
		<tbody>
			<tr>
				<td>
				<div class="input-box">
					<select name="product[product_id][]" onchange="changeUnitPrice(this)" style="margin:0">
					<?php foreach($products as $product):?>
						<option value="<?php echo $product['product_id']?>"><?php echo $product['product_name']?></option>
					<?php endforeach;?>
					</select>
				</div>
				</td>
				<td>
				<div class="input-box">
					<input type="number" name="product[unit_price][]" value="<?php echo $product['unit_price']?>" readonly class="unit_price"style="margin:0"/>
				</div>
				</td>
				<td>
				<div class="input-box">
					<input type="number" name="product[quantity][]" onkeyup = "calculateTotalPrice(this)" class="quantity"style="margin:0"/>
				</div>
				</td>
				<td>
				<div class="input-box">
					<input type="number" name = "product[total_price][]" class="total_price" onchange="updateUnitPrice(this)"style="margin:0"/>
				</div>
				</td>
			</tr>
		</tbody>
	</table>
		<div class="input-box">
			<input type="button" value="Add New Product" class="add-new-row" onclick="addNewRow()"/>
		</div>

	<div class="input-box">
	<input type="submit" value="Save"/>
	</div>
</form>
<?php endif;?>
<script type="text/javascript">
function changeUnitPrice(p)
{
	var product_id = $(p).val();
	$(p).parent().parent().find('.unit_price').val(products[product_id]);
}
function addNewRow()
{
	var html = $('table tbody tr').html();
	$('table tbody').append('<tr>'+html+'</tr>');

}

function calculateTotalPrice(quantity)
{
	var q = $(quantity).val();
	var u = $(quantity).parent().parent().find('.unit_price').val();
	var t = q * u;
	$(quantity).parent().parent().find('.total_price').val(t);
}

function updateUnitPrice(total_price)
{
	var t = $(total_price).val();
	var q = $(total_price).parent().parent().find('.quantity').val();
	var u = t/q;
	$(total_price).parent().parent().find('.unit_price').val(u);

}
</script>