<div class="row">
	<div class="col-lg-6 col-lg-offset-3">
	<div class="row">
                    <!--This Can be used to show filter later on. Removed Based on Subodh's requirement -->
		<div class="col-lg-4" style='display:none'>
			<select id="status" class="form-control" style="margin:0;display:none" onchange="FilterPO()" >
				<option value="">All</option>
				<option value="1">In Progress</option>
				<option value="3">Canceled</option>
			</select>
		</div>
	<div class="col-lg-12">
		<a href="<?php echo ADMIN_URL.'purchaseorders/new'?>" class="btn btn-primary">New Purchase Order</a>
		<a href="javascript:void(0)" class="btn btn-danger canceled" onclick='ShowCanceled()'>Canceled Purchase Orders</a>
                <a href="javascript:void(0)" class="btn btn-info all" onclick='ShowAll()' onclick='ShowCanceled()'>All Purchase Orders</a>
	</div>
	</div>
	<div class="list-group" id="purchase-orders">
	<h4 class="list-group-item active">Purchase Orders</h4>
	<?php if(isset($purchase_orders) and $purchase_orders):?>
		<?php foreach($purchase_orders as $po):?>
			<a class="list-group-item" href="<?php echo ADMIN_URL.'purchaseorders/complete/'.$po['id']?>"><?php echo $po['sku'];?>

			<span class="badge "><?php echo $po['po_entered_date'];?></span>
			<?php if($po['po_status'] == 1){$class = 'primary';} else if($po['po_status'] == 2){$class="success";} else{$class = "danger";}?>
			<span class="badge badge-<?php echo $class?>"><?php echo getModel('postatus')->getStatusName($po['po_status']);?></span>
			</a>
		<?php endforeach;?>
	<?php else:?>
		<p class="list-group-item text-center">No Data Found</p>
	<?php endif;?>
	</div>
	</div>
</div>

<script type="text/javascript">
	function FilterPO()
	{
		var status = $('#status').val();
		 $.ajax({
            url:'<?php echo ADMIN_URL.'purchaseorders/getFilteredPO'?>',
            method:'POST',
            data:{'status':status},
            success:function(response){
                $('#purchase-orders').html(response);
            }
        });
	}
        
        $(document).ready(function(){
            $('#status').val(1);
            FilterPO();
        });
        
        function ShowCanceled()
        {
            $('#status').val(3);
            FilterPO();
        }
        function ShowAll()
        {
            $('#status').val('1');
            FilterPO();
        }
        
</script>