<div class="rabbits">

<?php $rabbits = getModel('rabbit')->getCollection();?>
<?php $litter_array = array();?>
<?php $parents_to_be_array = array();?>
<?php $products_to_be_array = array();?>
<?php $parents_array = array();?>
<?php foreach($rabbits as $rabbit):?>
	<?php $r = getModel('product')->load($rabbit['product_id']);?>
	<?php if($r['attributes']['is_litter'] == 'yes'):?>
		<?php $litter_array[$r['attributes']['rabbit_family_id']][$r['attributes']['parent_doe_id']][] = $r['product_id'];?>
	<?php elseif($r['attributes']['rabbit_group'] == 'Parents to be'):?>
		<?php $parents_to_be_array[$r['attributes']['rabbit_family_id']][] = $r['product_id'];?>
	<?php elseif($r['attributes']['rabbit_group'] == 'Products to be '):?>
		<?php $products_to_be_array[$r['attributes']['rabbit_family_id']][] = $r['product_id'];?>
	<?php else:?>
		<?php $parents_array[$r['attributes']['rabbit_family_id']][] = $r['product_id'];?>
	<?php endif;?>
<?php endforeach;?>


<form method="post" action="<?php echo ADMIN_URL.'rabbits/performMating'?>">
<?php foreach($parents_array as $family => $rabbits):?>
<ul>
	<h3><?php echo 'Family '.$family;?></h3>
	<?php foreach($rabbits as $rabbit_id):?>
	<?php $rabbit = getModel('rabbit')->load($rabbit_id);?>

	<?php $dob = new DateTime($rabbit['rabbit_dob']);?>
			<!--Parents-->
				<?php $today = new DateTime(date('Y-m-d'));?>
				<?php if(isset($rabbit['rabbit_latest_mate_date'])):?>
				<?php $mate_date = new DateTime($rabbit['rabbit_latest_mate_date']);?>
				<?php $diff = $today->diff($dob)->format("%a");?>
				<?php $mate_diff = $today->diff($mate_date)->format("%a");?>
				<?php endif;?>
				<?php if(isset($rabbit['rabbit_latest_pregnant_date'])):?>
				<?php $preg_date = new DateTime($rabbit['rabbit_latest_pregnant_date']);?>
				<?php $diff = $today->diff($dob)->format("%a");?>
				<?php $preg_diff = $today->diff($preg_date)->format("%a");?>
				<?php endif;?>
				<?php if(isset($rabbit['rabbit_latest_birth_date'])):?>
				<?php $wean_date = new DateTime($rabbit['rabbit_latest_birth_date']);?>
				<?php $diff = $today->diff($dob)->format("%a");?>
				<?php $wean_diff = $today->diff($wean_date)->format("%a");?>
				<?php endif;?>
				<?php $status = null;?>

	<?php if($rabbit['rabbit_gender'] == 'Male'):?>
		<?php $status = "available_to_mate";?>
	<?php elseif($rabbit['rabbit_gender'] == 'Female'):?>
		<?php if(!isset($rabbit['rabbit_latest_mate_date'])):?>
			<?php $status = "available_to_mate";?>
		<?php elseif((!isset($rabbit['rabbit_latest_pregnant_date']) or !$rabbit['rabbit_latest_pregnant_date']) and $mate_diff < 12 or $mate_diff > 15):?>
			<?php $status = "wait_for_pregnancy"?>
		<?php elseif((!isset($rabbit['rabbit_latest_pregnant_date']) or !$rabbit['rabbit_latest_pregnant_date']) and ($mate_diff >= 12 and $mate_diff <= 15)):?>
			<?php $status = "check_for_pregnancy";?>
		<?php elseif((!isset($rabbit['rabbit_latest_birth_date']) or !$rabbit['rabbit_latest_birth_date']) and ($preg_diff >= 27 and $preg_diff <= 31)):?>
			<?php $status = "add_litters";?>
		<?php elseif(!isset($rabbit['rabbit_latest_birth_date']) or !$rabbit['rabbit_latest_birth_date'] or $preg_diff < 27 or $preg_diff > 31):?>		
			<?php $status = "wait_for_birth"?>
		<?php elseif((!isset($rabbit['rabbit_latest_weaning_date']) or !$rabbit['rabbit_latest_weaning_date'])and ($wean_diff >= 21 and $wean_diff <= 28)):?>
			<?php $status = "time_for_weaning"?>
		<?php elseif(!isset($rabbit['rabbit_latest_weaning_date']) or !$rabbit['rabbit_latest_weaning_date'] or $wean_diff < 21 or $wean_diff > 28):?>
			<?php $status = "wait_for_weaning"?>
		<?php endif;?>
	<?php endif;?>

		
		<li>
		<div class="rabbit <?php echo $status?>">
		<div class="rabbit_click">
			<p><?php echo $rabbit['product_name'];?></p>
			<p><?php echo $rabbit['rabbit_gender']?></p>
		</div>
		<input type="radio" name="family_<?php echo $rabbit['rabbit_gender']?>"value="<?php echo $rabbit['product_id']?>" onchange="checkToMate(this,<?php echo $family?>)"/>
		<a href="javascript:void(0)" class="select" onclick="selectRabbit(this,<?php echo $family?>)">Select</a>
		</div>
		<a class='ajax' href="<?php echo ADMIN_URL.'rabbits/listActions/'.$rabbit_id?>" style="display:none">Actions</a>
		</li>
	<?php endforeach;?>
	<input type="submit" value="Mate" disabled class="submit"/>
	<?php if(isset($litter_array[$family])):?>
	<?php foreach($litter_array[$family] as $litters):?>
		<?php $litter = getModel('rabbit')->load($litters[0]);?>
		<?php $wean_date = new DateTime($litter['rabbit_latest_weaning_date']);?>
		<?php $cull_diff = $today->diff($wean_date)->format("%a");?>
		<?php $status = null;?>
		<?php if($cull_diff <= 0):?>
			<?php $status = "wait_for_culling"?>
		<?php else:?>
			<?php $status = "time_for_culling"?>
		<?php endif;?>
		<li>
			<div class="rabbit <?php echo $status?>">
			<div class="rabbit_click">
				<p>Litters</p>
			</div>
			</div>
			<a class='ajax' href="<?php echo ADMIN_URL.'rabbits/listActions/'.$litters[0]?>" style="display:none">Actions</a>
		</li>
	<?php endforeach;?>
	<?php endif;?>
	<?php if(isset($parents_to_be_array[$family])):?>
	<h4>Parents to be</h4>
	<?php foreach($parents_to_be_array[$family] as $rabbits):?>
	<li>
	<?php $rabbit = getModel('rabbit')->load($rabbits);?>
	<?php $group_diff = $today->diff(new DateTime($rabbit['rabbit_latest_culling_date']))->format("%a");?>
	<?php $status = null;?>	
	<?php if($group_diff >= 90 and $group_diff <=120):?>
		<?php $status = 'time_for_grouping';?>
	<?php else:?>
		<?php $status = 'wait_for_grouping';?>
	<?php endif;?>
	<div class="rabbit <?php echo $status?>">
		<div class="rabbit_click">
			
			<p><?php echo $rabbit['product_name'];?></p>
		</div>		
	</div>
	<a class='ajax' href="<?php echo ADMIN_URL.'rabbits/listActions/'.$rabbit['product_id']?>" style="display:none">Actions</a>
	</li>
	<?php endforeach;?>
	<?php endif;?>

	<?php if(isset($products_to_be_array[$family])):?>
	<h4>Product to be</h4>
	<?php foreach($products_to_be_array[$family] as $rabbits):?>
	<li>
	<?php $rabbit = getModel('rabbit')->load($rabbits);?>
	<?php $group_diff = $today->diff(new DateTime($rabbit['rabbit_latest_culling_date']))->format("%a");?>
	<?php $status = null;?>	
	<?php if($group_diff >= 90 and $group_diff <=120):?>
		<?php $status = 'time_for_grouping';?>
	<?php else:?>
		<?php $status = 'wait_for_grouping';?>
	<?php endif;?>
	<div class="rabbit <?php echo $status?>">
		<div class="rabbit_click">
			
			<p><?php echo $rabbit['product_name'];?></p>
		</div>		
	</div>
	<a class='ajax' href="<?php echo ADMIN_URL.'rabbits/listActions/'.$rabbit['product_id']?>" style="display:none">Actions</a>
	</li>
	<?php endforeach;?>
	<?php endif;?>
</ul>
<?php endforeach;?>
</form>




</div>
<script type="text/javascript">
			$(document).ready(function(){
				$('.ajax').colorbox({top:"25%",width:"50%"});
				$('.rabbit_click').click(function(){
					$(this).parent().parent().find('a.ajax').trigger("click");
				});
			});
			function checkToMate(radio, family_id)
			{
				var parent = $(radio).parent().parent().parent();
				if($(parent).find('input[name=family_Male]').is(':checked') && $(parent).find('input[name=family_Female]').is(':checked'))	
				{
					$(parent).find('input.submit').removeAttr('disabled');
				}
			}

			function selectRabbit(link,family_id)
			{
				var parent = $(link).parent().find('input[type=radio]');
				if($(parent).attr('checked') == true)
					$(parent).attr('checked',false);
				else
				{
					$(parent).prop('checked',true);
					checkToMate(parent, family_id);
				}
			}
			</script>