<div class="row">
    <div class="col-lg-12">
        <?php foreach($products as $product):?>
            <h3><?php echo $product['product_name'];?></h3>
            <form method='post' action='<?php echo ADMIN_URL.'dailyfeeds/dailyfeedpost'?>'>
                <input type='hidden' name='product_id' value='<?php echo $product['product_id'];?>'/>
                <?php foreach($feeding_groups as $fg):?>
                    <?php if($fg['feeding_group'] != 'litter'):?>
                <?php $qty = getModel('dailyfeed')->getDailyFeedQuantity($product['product_id'], $fg['id'], 'NULL');?>
                            <label for="feeding_groups[<?php echo $fg['id']?>]"><?php echo $fg['name'];?></label>
                            <input type="text" name="feeding_groups[<?php echo $fg['id']?>]" class="form-control" value='<?php echo $qty?>'/>
                    <?php else:?>
                            <label for="feeding_groups[<?php echo $fg['id']?>]"><?php echo $fg['name'];?></label>
                            <table class='table table-hover'>
                                <thead>
                                    <?php foreach($litter_days as $ld):?>
                                        <th><?php echo $ld['name'];?></th>
                                    <?php endforeach;?>
                                </thead>
                                <tbody>
                                    <tr>
                                    <?php foreach($litter_days as $ld):?>
                                        <?php $qty = getModel('dailyfeed')->getDailyFeedQuantity($product['product_id'], $fg['id'], $ld['id']);?>
                                        <td><input type='text' name='litter_days[<?php echo $ld['id']?>]' value='<?php echo $qty?>'/></td>
                                    <?php endforeach;?>
                                    </tr>
                                </tbody>
                            </table>
                    <?php endif;?>
                <?php endforeach;?>
                    <input type='submit' value='Save'/>
            </form>
        <?php endforeach;?>
    </div>
</div>