<div class='row'>
<div class='col-lg-12'>
    <?php foreach($products as $product):?>
    <h3><?php echo $product['product_name'];?></h3>
<form method='post' action='<?php echo ADMIN_URL.'dailyfeeds/dailyfeedpost'?>'>
    <input type='hidden' name='product_id' value='<?php echo $product['product_id'];?>'/>
    <table class='table'>
        <thead>
        <th class='col-lg-1'></th>
        <?php foreach($weight_groups as $wg):?>
        <th class='col-lg-1'><?php echo $wg['name'];?></th>
        <?php endforeach;?>
        </thead>
        <tbody>
            <?php foreach($feeding_groups as $fg):?>
            <tr>
                <td><?php echo $fg['name'];?></td>
                <?php foreach($weight_groups as $wg):?>
                <?php $qty = getModel('dailyfeed')->getDailyFeedQuantity($product['product_id'], $wg['id'], $fg['id']);?>
                <?php if($qty == false):?>
                    <td><input type='text' name='weight_group[<?php echo $fg['id']?>][<?php echo $wg['id']?>]'/></td>
                <?php else:?>
                    <td><input type='text' name='weight_group[<?php echo $fg['id']?>][<?php echo $wg['id']?>]' value='<?php echo $qty['quantity']?>'/></td>
                <?php endif;?>
                <?php endforeach;?>
            </tr>
            <?php endforeach;?>
        </tbody>
    </table>
    <input type='submit' value='save'/>
</form>
<?php endforeach; ?>
</div>
</div>