<div class="row">
    <div class="col-lg-10 col-lg-offset-1">
        <div class="row">
            <div class="col-lg-12">
                <?php foreach ($products as $product): ?>
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <h3 class="panel-title"><?php echo $product['product_name']; ?></h3>
                        </div>
                        <div class="panel-body">
                            <form method='post' action='<?php echo ADMIN_URL . 'dailyfeeds/dailyfeedpost' ?>'>
                                <input type='hidden' name='product_id' value='<?php echo $product['product_id']; ?>'/>
                                <?php foreach ($feeding_groups as $fg): ?>
                                    <?php if ($fg['feeding_group'] != 'litter'): ?>
                                        <label for="feeding_groups[<?php echo $fg['id'] ?>]"><?php echo $fg['name']; ?></label>
                                        <div class="row">
                                            <div class="col-lg-2">
                                                <?php $qty = getModel('dailyfeed')->getDailyFeedQuantity($product['product_id'], $fg['id'], 'NULL'); ?>
                                                <input type="text" name="feeding_groups[<?php echo $fg['id'] ?>]" class="form-control" value='<?php echo $qty ?>'/>
                                            </div>
                                            <div class="col-lg-2">
                                                <span><?php echo getModel('uom')->getUnitSymbol($product['product_weight_unit']) ?></span>
                                            </div>
                                        </div>
                                    <?php else: ?>
                                        <label for="feeding_groups[<?php echo $fg['id'] ?>]"><?php echo $fg['name']; ?></label>
                                        <table class='table table-hover'>
                                            <thead>
                                                <?php foreach ($litter_days as $ld): ?>
                                                <th class="col-lg-1"><?php echo $ld['name']; ?></th>
                                            <?php endforeach; ?>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <?php foreach ($litter_days as $ld): ?>
                                                        <?php $qty = getModel('dailyfeed')->getDailyFeedQuantity($product['product_id'], $fg['id'], $ld['id']); ?>
                                                        <td><input type='text' class='form-control' name='litter_days[<?php echo $ld['id'] ?>]' value='<?php echo $qty ?>'/></td>
                                                        <?php endforeach; ?>
                                                </tr>
                                            </tbody>
                                        </table>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                                <input type='submit' value='Save'/>
                            </form>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>