<style>
td input{margin:0;}
</style>
<form method="post" action="<?php echo ADMIN_URL.'dailyfeeds/updateDailyFeed'?>">


<?php if(isset($dailyfeeds) and $dailyfeeds):?>
	<table>
	<thead>
	<th>Feeding Group</th>
	<th>0.6 kg - 0.7 kg</th>
	<th>1 kg - 2 kg</th>
	<th>2 kg - 3 kg</th>
	<th>3 kg - 4 kg</th>
	<th>5 kg - 5 kg</th>
	<th>5 kg +</th>
	</thead>
	<tbody>
	<?php foreach($dailyfeeds as $dailyfeed):?>
		<?php $option = getModel('option')->load($dailyfeed['feeding_group_id']);?>
		<input type="hidden" name="update" value="update"/>
		<input type="hidden" name="feeding_group[]" value="<?php echo $dailyfeed['feeding_group_id']?>"/>
		<input type="hidden" name="daily_feed_id[]" value="<?php echo $dailyfeed['daily_feed_id']?>"/>
		<tr>
		<td><?php echo $option['value'];?></td>
		<td><input type="text" name="weight_1[]" value="<?php echo $dailyfeed['06_07kg']?>"/></td>
		<td><input type="text" name="weight_2[]" value="<?php echo $dailyfeed['1_2kg']?>"/></td>
		<td><input type="text" name="weight_3[]" value="<?php echo $dailyfeed['2_3kg']?>"/></td>
		<td><input type="text" name="weight_4[]" value="<?php echo $dailyfeed['3_4kg']?>"/></td>
		<td><input type="text" name="weight_5[]" value="<?php echo $dailyfeed['4_5kg']?>"/></td>
		<td><input type="text" name="weight_6[]" value="<?php echo $dailyfeed['5_kg']?>"/></td>
		</tr>		
	<?php endforeach;?>
	</tbody>
	</table>
	<input type="submit" value="Save"/>	
<?php else:?>
	<table>
	<thead>
	<th>Feeding Group</th>
	<th>0.6 kg - 0.7 kg</th>
	<th>1 kg - 2 kg</th>
	<th>2 kg - 3 kg</th>
	<th>3 kg - 4 kg</th>
	<th>5 kg - 5 kg</th>
	<th>5 kg +</th>
	</thead>
	<tbody>
	<?php foreach($feeding_groups as $group):?>
		<input type="hidden" name="feeding_group[]" value="<?php echo $group['id']?>"/>
		<tr>
		<td><?php echo $group['value'];?></td>
		<td><input type="text" name="weight_1[]"/></td>
		<td><input type="text" name="weight_2[]"/></td>
		<td><input type="text" name="weight_3[]"/></td>
		<td><input type="text" name="weight_4[]"/></td>
		<td><input type="text" name="weight_5[]"/></td>
		<td><input type="text" name="weight_6[]"/></td>
		</tr>
	<?php endforeach;?>
	</tbody>
	</table>
	<input type="submit" value="Save"/>
<?php endif;?>
</form>
