<?php if (isset($dead_rabbits)): ?>
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <table class="table table-hover">
                <thead>
                <th>ID</th>
                <th>Rabbit/Litter</th>
                <th>Dead on</th>
                <th>Reason</th>
                </thead>
                <tbody>
                    <?php foreach ($dead_rabbits as $dead_rabbit): ?>
                        <tr>
                            <td><?php echo $dead_rabbit['death_id']; ?></td>
                            <?php if ($dead_rabbit['rabbit_id']): ?>
                                <td><?php echo $dead_rabbit['rabbit_id']; ?></td>
                            <?php else: ?>
                                <td><?php echo $dead_rabbit['litter_id']; ?></td>
                            <?php endif; ?>
                            <td><?php echo $dead_rabbit['death_date']; ?></td>
                            <td><?php echo $dead_rabbit['reason']; ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
<?php endif; ?>
