<?php if ($rabbit): ?>
    <div class="row">
        <div class = "rabbit col-lg-4 col-md-4 col-sm-6 col-xs-12">
            <?php if ($rabbit['is_dead'] == 1): ?>
                <div class="alert alert-danger">
                    <p>Rabbit is Dead</p>
                </div>
            <?php elseif ($rabbit['is_sick'] == 1): ?>
                <div class="alert alert-warning">
                    <p>Rabbit is Sick</p>
                </div>
            <?php endif; ?>
            <div class="list-group">
                <a href="javascript:void(0)" class="list-group-item active text-center"><h3>Rabbit <?php echo $rabbit['product_id'] ?></h3></a> 
                <a href="#" class="list-group-item">Family ID: <span class="badge badge-primary pull-right"><?php echo $rabbit['rabbit_family_id'] ?></span></a> 
                <a href="#" class="list-group-item">Gender: <span class="badge badge-primary pull-right"><?php echo $rabbit['rabbit_gender'] ?></span></a> 
                <a href="#" class="list-group-item">Group: <span class="badge badge-primary pull-right"><?php echo $rabbit['rabbit_group'] ?></span></a> 
                <?php if ($rabbit['parent_doe_id'] != 0): ?>
                    <a href="#" class="list-group-item">Parent Doe: <span class="badge badge-primary pull-right"><?php echo $rabbit['parent_doe_id'] ?></span></a> 
                <?php endif; ?>
                <?php if ($rabbit['parent_buck_id'] != 0): ?>
                    <a href="#" class="list-group-item">Parent Buck: <span class="badge badge-primary pull-right"><?php echo $rabbit['parent_buck_id'] ?></span></a> 
                <?php endif; ?>
                <a href="#" class="list-group-item">Date of Birth: <span class="badge badge-primary pull-right"><?php echo $rabbit['rabbit_dob'] ?></span></a>
                <?php if (isset($rabbit['rabbit_latest_mate_date'])): ?>
                    <a href="#" class="list-group-item">Recent Mate Date: <span class="badge badge-primary pull-right"><?php echo $rabbit['rabbit_latest_mate_date'] ?></span></a> 
                <?php endif; ?>
                <?php if (isset($rabbit['rabbit_latest_pregnant_date'])): ?>
                    <a href="#" class="list-group-item">Recent Pregnant Date: <span class="badge badge-primary pull-right"><?php echo $rabbit['rabbit_latest_pregnant_date'] ?></span></a> 
                <?php endif; ?>
                <?php if (isset($rabbit['rabbit_latest_birth_date'])): ?>
                    <a href="#" class="list-group-item">Recent Birth Date: <span class="badge badge-primary pull-right"><?php echo $rabbit['rabbit_latest_birth_date'] ?></span></a> 
                <?php endif; ?>
                <?php if (isset($rabbit['rabbit_latest_weaning_date'])): ?>
                    <a href="#" class="list-group-item">Weaning Date: <span class="badge badge-primary pull-right"><?php echo $rabbit['rabbit_latest_weaning_date'] ?></span></a> 
                <?php endif; ?>
                <?php if (isset($rabbit['rabbit_latest_culling_date'])): ?>
                    <a href="#" class="list-group-item">Culling Date: <span class="badge badge-primary pull-right"><?php echo $rabbit['rabbit_latest_culling_date'] ?></span></a> 
                <?php endif; ?>
                <a href="#" class="list-group-item">Feeding Group: <span class="badge badge-primary pull-right"><?php echo $rabbit['rabbit_feeding_group'] ?></span></a>
            </div>
        </div>
        <div class="rabbit-actions col-lg-1 col-md-2 col-sm-2 col-xs-12">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <button type="button" data="sick_form1" class="action_btn sick_btn btn btn-primary btn-block" <?php echo ($rabbit['is_sick'] == 1 or $rabbit['is_dead'] == 1 ) ? 'disabled' : null ?>>Sick</button>
                    <button type="button" data="death_form" class="action_btn death_btn btn btn-primary btn-block" <?php echo ($rabbit['is_dead'] == 1 ) ? 'disabled' : null ?>>Death</button>
                    <button type="button" data="shift_form" class="action_btn shift_btn btn btn-primary btn-block" <?php echo ($rabbit['is_dead'] == 1 ) ? 'disabled' : null ?>>Shift</button>
                    <button type="button" data="slaughter_form" class="action_btn slaughter_btn btn btn-primary btn-block" <?php echo ($rabbit['is_dead'] == 1 ) ? 'disabled' : null ?>>Slaughter</button>
                </div>
            </div>
        </div>
        <div class="rabbit-actions-form col-lg-4 col-md-4 col-sm-4 col-xs-12">

            <form method="post" action="<?php echo ADMIN_URL . 'rabbit/sick' ?>" style="display:none" id="sick_form1">
                <fieldset>
                    <input type="hidden" name="rabbit_id" value="<?php echo $rabbit['product_id']; ?>"/>
                    <div class="row">
                        <div class="col-lg-12">
                            <select name="sick_reason_id" class="required" onchange="CheckSickReason(this)"  style="width: 100%;height: 35px;border-radius: 5px;width: 100%;margin:0">
                                <option value='' disabled selected style='display:none;'>Select A Reason</option>
                                <?php if ($sick_reasons): ?>
                                    <?php foreach ($sick_reasons as $reason): ?>
                                        <option value="<?php echo $reason['id']; ?>"><?php echo $reason['reason']; ?></option>
                                    <?php endforeach; ?>
                                    <option value="-1">Other</option>
                                <?php endif; ?>
                            </select>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <input name="sick_from" type="text" class=" form-control required" placeholder="Sick Date" id="sick_from">
                        </div>
                        <script>
                            $('#sick_from').datepicker({
                                format: 'yyyy-mm-dd',
                                todayBtn: 'linked'
                            });
                        </script>
                    </div>
                    <div class="row other_reason" style="display:none">
                        <div class="col-lg-12">
                            <div class="row">
                                <div class="col-lg-12">
                                    <input name="sick_reason" type="text" class=" form-control required" placeholder="Mention Reason">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-12">
                                    <textarea name="sick_reason_desc" class="form-control required" rows="3" placeholder="Description"></textarea>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-lg-4 col-md-4 col-sm-4">
                            <input type="submit" value="Send" class="submit btn btn-default btn-block sick_submit_btn"/>
                        </div>
                    </div>
                    <div class="row">
                        <div id="sick_response"></div>
                    </div>
                </fieldset>
            </form>
            <form method="post" action = "<?php echo ADMIN_URL . 'rabbit/death' ?>" class="death_form" id = "death_form" style="display:none">
                <fieldset>
                    <input type="hidden" name="rabbit_id" value="<?php echo $rabbit['product_id']; ?>"/>
                    <div class="row">
                        <div class="col-lg-12">
                            <select name="death_reason_id" class="required" onchange="CheckDeathReason(this)" style="width: 100%;height: 35px;border-radius: 5px;width: 100%;margin:0">
                                <option value='' disabled selected style='display:none;'>Select A Reason</option>
                                <?php if ($death_reasons): ?>
                                    <?php foreach ($death_reasons as $reason): ?>
                                        <option value="<?php echo $reason['id']; ?>"><?php echo $reason['reason']; ?></option>
                                    <?php endforeach; ?>
                                    <option value="-1">Other</option>
                                <?php endif; ?>
                            </select>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <input name="dead_on" type="text" class=" form-control required" placeholder="Death Date" id="dead_on">
                        </div>
                        <script>
                            $('#dead_on').datepicker({
                                format: 'yyyy-mm-dd',
                                todayBtn: 'linked'
                            });
                        </script>
                    </div>
                    <div class="row other_reason" style="display:none">
                        <div class="col-lg-12">
                            <div class="row">
                                <div class="col-lg-12">
                                    <input name="death_reason" type="text" class=" form-control required" placeholder="Mention Death Reason">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-12">
                                    <textarea name="death_reason_desc" class="form-control required" rows="3" placeholder="Description"></textarea>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-lg-4 col-md-4 col-sm-4">
                            <input type="submit" value="Send" class="submit btn btn-default btn-block sick_submit_btn"/>
                        </div>
                    </div>
                    <div class="row">
                        <div id="sick_response"></div>
                    </div>
                </fieldset>
            </form>
            <form method="post" class="shift_form" id="shift_form" action = "<?php echo ADMIN_URL . 'rabbit/shift' ?>" style="display:none">
                <fieldset>
                    <input type="hidden" name="rabbit_id" value="<?php echo $rabbit['product_id']; ?>"/>
                    <div class="row">
                        <div class="col-lg-12">
                            <select name="rabbit_group" class="required" style="width: 100%;height: 35px;border-radius: 5px;width: 100%;margin:0">
                                <option value='' disabled selected style='display:none;'>Select A Group</option>
                                <?php if ($rabbit['rabbit_group'] == 'Parents'): ?>
                                    <option value="20">Products</option>
                                    <!--                                    <option value="19">Parents to be</option>
                                                                        <option value="21">Products to be</option>-->
                                <?php elseif ($rabbit['rabbit_group'] == 'Products'): ?>
                                    <option value="18">Parents</option>
                                    <!--                                    <option value="19">Parents to be</option>
                                                                        <option value="21">Products to be</option>-->
                                <?php endif; ?>
                            </select>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <input name="shifted_on" type="text" class=" form-control required" placeholder="Shifted Date" id="shifted_on">
                        </div>
                        <script>
                            $('#shifted_on').datepicker({
                                format: 'yyyy-mm-dd',
                                todayBtn: 'linked'
                            });
                        </script>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <select name="shifting_reason_id" class="required" onchange="CheckShiftingReason(this)" style="width: 100%;height: 35px;border-radius: 5px;width: 100%;margin:0">
                                <option value='' disabled selected style='display:none;'>Select A Reason</option>
                                <?php if ($shifting_reasons): ?>
                                    <?php foreach ($shifting_reasons as $reason): ?>
                                        <option value="<?php echo $reason['id']; ?>"><?php echo $reason['reason']; ?></option>
                                    <?php endforeach; ?>
                                    <option value="-1">Other</option>
                                <?php endif; ?>
                            </select>
                        </div>
                    </div>
                    <div class="row other_reason" style="display:none">
                        <div class="col-lg-12">
                            <div class="row">
                                <div class="col-lg-12">
                                    <input name="shifting_reason" type="text" class=" form-control required" placeholder="Mention Shifting Reason">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-12">
                                    <textarea name="shifting_reason_desc" class="form-control required" rows="3" placeholder="Description"></textarea>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-lg-4 col-md-4 col-sm-4">
                            <input type="submit" value="Send" class="submit btn btn-default btn-block sick_submit_btn"/>
                        </div>
                    </div>
                    <div class="row">
                        <div id="sick_response"></div>
                    </div>
                </fieldset>
            </form>
            <form method="post" class="slaughter_form" style="display:none">
                <input type="text" placeholder="Reason Slaugther"/>
                <input type="submit" value="Save"/>
            </form>
        </div>
    </div>


    <script>

        $(document).ready(function () {
            $("#sick_form1").submit(function () {

                var url = $(this).attr('action'); // the script where you handle the form input.

                $.ajax({
                    type: "POST",
                    url: url,
                    data: $("#sick_form1").serialize(), // serializes the form's elements.
                    success: function (data)
                    {
                        var value = JSON.parse(data);
                        $(value.identifier).html(value.html);
                        $('#sick_form1').hide();
                        $('.rabbit-actions-form').prepend('<div class="alert alert-success alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button><p>Rabbit Made Sick</p></div>');
                    }
                });

                return false; // avoid to execute the actual submit of the form.
            });

            $("#death_form").submit(function () {

                var url = $(this).attr('action'); // the script where you handle the form input.

                $.ajax({
                    type: "POST",
                    url: url,
                    data: $("#death_form").serialize(), // serializes the form's elements.
                    success: function (data)
                    {
                        var value = JSON.parse(data);
                        $(value.identifier).html(value.html);
                        $('#death_form').hide();
                        $('.rabbit-actions-form').prepend('<div class="alert alert-danger alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button><p>Rabbit Dead</p></div>');
                    }
                });

                return false; // avoid to execute the actual submit of the form.
            });

            $("#shift_form").submit(function () {

                var url = $(this).attr('action'); // the script where you handle the form input.

                $.ajax({
                    type: "POST",
                    url: url,
                    data: $("#shift_form").serialize(), // serializes the form's elements.
                    success: function (data)
                    {
                        var value = JSON.parse(data);
                        $(value.identifier).html(value.html);
                        $('#shift_form').hide();
                        $('.rabbit-actions-form').prepend('<div class="alert alert-danger alert-success"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button><p>Rabbit Shifted</p></div>');
                    }
                });

                return false; // avoid to execute the actual submit of the form.
            });
        });

    </script>
    <script type="text/javascript">
        $(document).ready(function () {
            // $("select").selecter({
            //     label: "Select An Item"
            // });
            $('button.action_btn').click(function () {
                $('.rabbit-actions-form form').hide();
                $('.rabbit-actions-form form .other_reason').hide();
                $('.rabbit-actions-form form .required').removeAttr('required');
                var form = $(this).attr('data');
                $('#' + form).show();
            });


        });

        function CheckSickReason(select)
        {
            //alert($(select).val());
            if ($(select).val() == -1)
            {
                $('.other_reason').show();
                $('.other_reason .required').attr('required', '');
            }
            else
            {
                $('.other_reason').hide();
                $('.other_reason .required').removeAttr('required');
            }
            //alert($('select').val());
        }

        function CheckDeathReason(select)
        {
            //alert($(select).val());
            if ($(select).val() == -1)
            {
                $('.other_reason').show();
                $('.other_reason .required').attr('required', '');
            }
            else
            {
                $('.other_reason').hide();
                $('.other_reason .required').removeAttr('required');
            }
            //alert($('select').val());

        }
        function CheckShiftingReason(select)
        {
            //alert($(select).val());
            if ($(select).val() == -1)
            {
                $('.other_reason').show();
                $('.other_reason .required').attr('required', '');
            }
            else
            {
                $('.other_reason').hide();
                $('.other_reason .required').removeAttr('required');
            }
            //alert($('select').val());
        }

    </script>
<?php endif; ?>
