<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php if (isset($shifted_rabbits) and $shifted_rabbits): ?>
            <table class="table table-hover">
                <thead>
                <th>ID</th>
                <th>Rabbit</th>
                <th>Shifted From</th>
                <th>Shfited To</th>
                <th>Shifted on</th>
                <th>Reason</th>
                </thead>
                <tbody>
                    <?php foreach ($shifted_rabbits as $shifted_rabbit): ?>
                        <tr>
                            <td><?php echo $shifted_rabbit['shift_id']; ?></td>
                            <td><?php echo $shifted_rabbit['rabbit_id']; ?></td>
                            <td><?php echo $shifted_rabbit['shifted_from']; ?></td>
                            <td><?php echo $shifted_rabbit['shifted_to']; ?></td>
                            <td><?php echo $shifted_rabbit['shifted_date']; ?></td>
                            <td><?php echo $shifted_rabbit['reason']; ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        <?php else: ?>
            <div class="alert alert-success">
                <p>No Shifted Rabbits</p>
            </div>
        <?php endif; ?>
    </div>
</div>
