</div>
<div class="row">
    <div class="col-md-12">
        <div class="footer">
            <div class="container">
                <div class="clearfix">
                 
                    <!--                <dl class="footer-nav">
                                        <dt class="nav-title">PORTFOLIO</dt>
                                        <dd class="nav-item">
                                            <a href="#">Web Design</a>
                                        </dd>
                                        <dd class="nav-item">
                                            <a href="#">Branding &amp; Identity</a>
                                        </dd>
                                        <dd class="nav-item">
                                            <a href="#">Mobile Design</a>
                                        </dd>
                                        <dd class="nav-item">
                                            <a href="#">Print</a>
                                        </dd>
                                        <dd class="nav-item">
                                            <a href="#">User Interface</a>
                                        </dd>
                                    </dl>-->

                </div>
                <div class="footer-copyright text-center">Copyright © 2015 Manaram Technology.All rights reserved.</div>

            </div>

        </div>
    </div>