
<header>
	
</header>


<div id="top-wrap">
	<!--<div class="row">-->
			
		<div class="col-md-12">

			<div id="logo">
				Position for logo .
			</div><!--End logo-->

			<nav id="navigation">
				<div id="main-menu-container">
					<div class="navbar navbar-inverse navbar-static-top">
							<!--<button class="navbar-toggle" data-toggle="collapsed" data-target="#navheadercollapse">
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>-->
							<!--<div class="collapse navbar-collapse" id="navheadercollapse">-->
								<ul class="nav navbar-nav">
									<li class="active"><a href="#">Home</a></li>
									<li class="dropdown">
										<a class="dropdown-toggle diasbled" href="#">
											Catalog<b class="caret"></b>
										</a>
										<ul class="dropdown">
											<li><a href="<?php echo ADMIN_URL.'attributes'?>">Attributes</a></li>
											<li><a href="<?php echo ADMIN_URL.'attributesets'?>">Attribute Set</a></li>
											<li><a href="<?php echo ADMIN_URL.'products'?>">Products</a></li>
											<li><a href="#">Categories</a></li>
										</ul>
									</li>
								<li><a href="<?php echo ADMIN_URL.'rabbits'?>">Rabbits</a></li>
									<li class="dropdown">
										<a class="dropdown-toggle diasbled" href="<?php echo ADMIN_URL.'purchaseorders'?>">
											Purchase Orders<b class="caret"></b>
										</a>
										<ul class="dropdown">
											<li><a href="<?php echo ADMIN_URL.'purchaseorders/add'?>">Add New Purchase Order</a></li>
										</ul>
									</li>
									<!--<li><a href="#">Configuration</a></li>
									<li><a href="#">Costumers</a></li>
									<li><a href="#">Himalayan Dos Chews</a></li>
									<li><a href="#">Logout</a></li>-->
			 					</ul>
			 				</div>
				</div>
			</div>
		</nav>
	</div>
</div>
<!--End row-->
</div><!--End top-->
<body>
<div class="container">

<!-- <h1>Admin Header</h1>
<ul>
	<li><a href="<?php echo ADMIN_URL.'attributes'?>">Attributes</a></li>
	<li><a href="<?php echo ADMIN_URL.'attributesets'?>">Attribute Sets</a></li>
</ul> -->