
<!-- <script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script> -->
<nav class="navbar navbar-default navbar-fixed-top">
<div class="container">
      <div class="nav-container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Long Logo Name</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Catalog <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="<?php echo ADMIN_URL.'attributes'?>">Attributes</a></li>
                <li><a href="<?php echo ADMIN_URL.'attributesets'?>">Attribute Sets</a></li>
                <li><a href="<?php echo ADMIN_URL.'products'?>">Products</a></li>
              </ul>
            </li>
            <li><a href="<?php echo ADMIN_URL.'products'?>">Products</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Rabbits <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="<?php echo ADMIN_URL.'rabbit'?>">Rabbit Main Page</a></li>
                <li><a href="<?php echo ADMIN_URL.'rabbits'?>">Rabbit Family Page</a></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Purchase<span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="<?php echo ADMIN_URL.'purchasecategories'?>">Categories</a></li>
                <li><a href="<?php echo ADMIN_URL.'suppliers'?>">Suppliers</a></li>
                <li><a href="<?php echo ADMIN_URL.'purchaseproducts'?>">Products</a></li>
                <li><a href="<?php echo ADMIN_URL.'purchaseorders'?>">Purchase Orders</a></li>
              </ul>
            </li>
            <li><a href="<?php echo ADMIN_URL.'stock'?>">Stock</a></li>
            <li><a href="<?php echo ADMIN_URL.'dailyfeeds'?>">Daily Feeds</a></li>
          </ul>
          
        </div><!--/.nav-collapse -->
      </div><!--nav-container-->
</nav>
</div>
<body>
<div class="container-fluid main-container">

<!-- <h1>Admin Header</h1>
<ul>
	<li><a href="<?php echo ADMIN_URL.'attributes'?>">Attributes</a></li>
	<li><a href="<?php echo ADMIN_URL.'attributesets'?>">Attribute Sets</a></li>
</ul> -->