<div id="attributeset-edit" class="main-body">
<?php if(isset($attributeset) and $attributeset):?>
<?php extract($attributeset);?>
<form method = "post" action = "<?php echo ADMIN_URL.'attributesets/editpost/'?>">

	<div class="input-box">
		<input type="hidden" name="attribute_set_id" value="<?php echo $attribute_set_id?>"/>
		<label>Attribute Set Code</label>
		<input type="text" name="attribute_set_code" value="<?php echo $attribute_set_code?>"/>
	</div>

	<div class="input-box">
		<label>Attribute Set Name</label>
		<input type="text" name="attribute_set_name" value="<?php echo $attribute_set_name?>"/>
	</div>

	<div class="input-box">
		<label>Sort Order</label>
		<input type="text" name="sort_order" value="<?php echo $sort_order?>"/>
	</div>

	<div class="input-box">
		<label>Attribute:</label>
		<?php if(isset($attributes) and $attributes):?>
		<select name="attributes[]" multiple>
			<?php foreach($attributes as $attribute):?>
			<?php extract($attribute);?>
				<option value="<?php echo $attribute_id?>" <?php echo ($selected_attributes and in_array($attribute_id,$selected_attributes))?'selected':null;?>><?php echo $attribute_admin_label?></option>
			<?php endforeach;?>
		</select>
		<?php endif;?>
	</div>

	<input class="save" type="submit" value="save"/>
</form>
<?php else:?>
<h3>Invalid Attribute Set</h3>
<?php endif;?>
</div>