<!--<div class="popup-cover">-->
<div class="rabbit_popup">
<?php $rabbit = getModel('rabbit')->load($rabbit_id);?>

<?php $dob = new DateTime($rabbit['rabbit_dob']);?>
<?php $today = new DateTime(date('Y-m-d'));?>
<?php if(isset($rabbit['rabbit_latest_mate_date'])):?>
	<?php $mate_date = new DateTime($rabbit['rabbit_latest_mate_date']);?>
	<?php $diff = $today->diff($dob)->format("%a");?>
	<?php $mate_diff = $today->diff($mate_date)->format("%a");?>
	<?php $preg_diff = $today->diff($mate_date)->format("%a");?>
<?php endif;?>
<?php if(isset($rabbit['rabbit_latest_pregnant_date'])):?>
	<?php $preg_date = new DateTime($rabbit['rabbit_latest_pregnant_date']);?>
	<?php $diff = $today->diff($dob)->format("%a");?>
	<?php $preg_diff = $today->diff($mate_date)->format("%a");?>
<?php endif;?>
<?php if(isset($rabbit['rabbit_latest_birth_date'])):?>
	<?php $wean_date = new DateTime($rabbit['rabbit_latest_birth_date']);?>
	<?php $diff = $today->diff($dob)->format("%a");?>
	<?php $wean_diff = $today->diff($wean_date)->format("%a");?>
<?php endif;?>

<?php if((isset($rabbit['rabbit_group']) and strtolower($rabbit['rabbit_group']) == 'parents to be') and (!isset($rabbit['is_litter']) or strtolower($rabbit['is_litter']) == 'no')):?>
	<div class="status"><h3>Parents To Be</h3></div>
	<p><?php echo $rabbit['rabbit_latest_culling_date'];?></p>
	<?php $gender = $rabbit['rabbit_gender'];?>
	<?php $group_diff = $today->diff(new DateTime($rabbit['rabbit_latest_culling_date']))->format("%a");?>
	<?php if($group_diff >= 90 and $group_diff <= 120):?>
		<?php getModel('genealogy')->changeStatus($rabbit_id, 1);?>

		<?php $available_families = getModel('family')->getAvailableFamilies($gender,$rabbit['product_id']);?>
		<?php if($available_families):?>
			<form method="post" action="<?php echo ADMIN_URL.'rabbits/addToFamily'?>">
				<input type="hidden" name="rabbit_id" value="<?php echo $rabbit['product_id']?>"/>
				<select name="family_id">
					<?php foreach($available_families as $av_family):?>
						<option value="<?php echo $av_family?>"><?php echo $av_family;?></option>
					<?php endforeach;?>
				</select>
				<input type="submit" value="Add to Family"/>
			</form>
			<a href="<?php echo ADMIN_URL.'rabbits/addToNewFamily/'.$rabbit['product_id']?>">Add this rabbit to a new family</a>
		<?php else:?>
			<a href="<?php echo ADMIN_URL.'rabbits/addToNewFamily/'.$rabbit['product_id']?>">Add this rabbit to a new family</a>
		<?php endif;?>



	<?php endif;?>
<?php elseif((isset($rabbit['rabbit_group']) and strtolower($rabbit['rabbit_group']) == 'products to be ') and (!isset($rabbit['is_litter']) or strtolower($rabbit['is_litter']) == 'no')):?>
	<div class="status"><h3>Products To Be</h3></div>
	<?php $group_diff = $today->diff(new DateTime($rabbit['rabbit_latest_culling_date']))->format("%a");?>
	<?php if($group_diff >= 60 and $group_diff <=90):?>
		<a href="<?php echo ADMIN_URL.'rabbits/moveToProducts/'.$rabbit['product_id']?>">Move this rabbits to product</a>
	<?php endif;?>
<?php else:?>
	<?php if($rabbit['rabbit_gender'] == 'Female'):?>
		<?php if(!isset($rabbit['is_litter']) or strtolower($rabbit['is_litter']) == 'no'):?>
			<?php if(!isset($rabbit['rabbit_latest_mate_date'])):?>
				<div class="status"><h3>Available For Mating</h3></div>
			<?php elseif((!isset($rabbit['rabbit_latest_pregnant_date']) or !$rabbit['rabbit_latest_pregnant_date']) and ($mate_diff >= 12 and $mate_diff <= 25)):?>
				<div class="status"><h3>Is this rabbit pregnant?</h3></div>
				<a href="<?php echo ADMIN_URL.'rabbits/pregnant/'.$rabbit_id?>">Yes</a>
				<a href="<?php echo ADMIN_URL.'rabbits/notpregnant/'.$rabbit_id?>">No</a>
				<!-- Add Not Pregnant Reason Script HERE -->
			<?php elseif((!isset($rabbit['rabbit_latest_pregnant_date']) or !$rabbit['rabbit_latest_pregnant_date']) and $mate_diff < 12):?>
				<div class="status"><h3>We have to wait <?php echo (12 - $mate_diff);?> to <?php echo (25 - $mate_diff)?> days to confirm pregnancy</h3></div>
			<?php elseif((!isset($rabbit['rabbit_latest_pregnant_date']) or !$rabbit['rabbit_latest_pregnant_date']) and $mate_diff > 25):?>
				<div class="status"><h3>Rabbit did not get pregnant. The status will change to available to mate.</h3></div>
				<!-- Add Not Pregnant Reason Script HERE -->
				<?php getModel('rabbit')->notPregnant($rabbit_id);?>
			<?php elseif((!isset($rabbit['rabbit_latest_birth_date']) or !$rabbit['rabbit_latest_birth_date']) and ($preg_diff >= 27 and $preg_diff <= 32)):?>
				<div class="status"><h3>How many litters are born?</h3></div>
				<div class="birth-form">
				<form method="post" action="<?php echo ADMIN_URL.'rabbits/addLitters'?>">
					<input type="hidden" name="parent_buck_id" value="<?php echo $rabbit['recently_mated_buck']?>"/>
					<input type="hidden" name="parent_rabbit_id" value="<?php echo $rabbit['product_id']?>"/>
					<input type="hidden" name="rabbit_family_id" value="<?php echo $rabbit['rabbit_family_id']?>"/>
					<select name="litters_count">
						<option value="1">1</option>
						<option value="2">2</option>
						<option value="3">3</option>
						<option value="4">4</option>
						<option value="5">5</option>
						<option value="6">6</option>
						<option value="7">7</option>
						<option value="8">8</option>
						<option value="9">9</option>
						<option value="10">10</option>
						<option value="11">11</option>
						<option value="12">12</option>
					</select>
					<input type="submit" value="Submit"/>
				</form>
				</div>
				<div class="still_birth">
				<p>Still Birth:</p><input type="checkbox"/>				
				</div>
			<?php elseif((!isset($rabbit['rabbit_latest_birth_date']) or !$rabbit['rabbit_latest_birth_date']) and $preg_diff < 27):?>
				<div class="status"><h3>We have to wait for <?php echo (27 - $preg_diff)?> to <?php echo (32 - $preg_diff)?> days for birth</h3></div>
				<div class="still_birth">
				<p>Still Birth:</p><input type="checkbox"/>				
				</div>
			<?php elseif((!isset($rabbit['rabbit_latest_birth_date']) or !$rabbit['rabbit_latest_birth_date']) and $preg_diff > 32):?>
				<div class="status"><h3>Days exceeded for birth by <?php echo ($preg_diff - 32)?> days. Rabbit will be available for Mating again</h3></div>
				<?php getModel('rabbit')->resetDates($rabbit_id);?>
			
			<?php elseif((!isset($rabbit['rabbit_latest_weaning_date']) or !$rabbit['rabbit_latest_weaning_date'])and ($wean_diff >= 21 and $wean_diff <= 28)):?>
				<div class="status"><h3>Time For Weaning</h3></div>
				<p>Is the weaning done?</p>
				<?php $litters = getModel('litter')->getCollection($rabbit['product_id']);?>
				<?php $litters_count = 0;?>
				<?php foreach($litters as $litter):?>
					<?php if(!$litter['rabbit_id']):?>
						<?php $litters_count++;?>
					<?php endif;?>
				<?php endforeach;?>
				<ul>
					<?php foreach($litters as $litter):?>
						<?php if($litter['litters_weaning_date'] == '0000-00-00'):?>
							<li><p><?php echo 'Litter '.$litter['litter_id'];?></p>
														<form method="post" action = "<?php echo ADMIN_URL.'rabbits/individualwean/'.$rabbit['product_id']?>">
								<div class="input-box">
									<input type="hidden" name="litter_id" value="<?php echo $litter['litter_id']?>"/>
									<input type="hidden" name="litters_count" value="<?php echo $litters_count?>"/>
									<select name="gender">
										<option value="11">Male</option>
										<option value="12">Female</option>
									</select>
									<div class="litterdeath">
										Is Litter Dead:<input type="checkbox" class="littercheck"> 	 <?php $litter_id=	$litter['litter_id']; ?>
										<a class='litterajax' href="<?php echo ADMIN_URL.'rabbits/deathlitterActions/'.$litter_id?>" style="display:none">Actions</a>
									</div>
									<input class="wean" type="submit" value="Wean"/>
								</div>
							</form>

							</li>
						<?php endif;?>
					<?php endforeach;?>
				</ul>

<!-- 				<form method="post" action = "<?php echo ADMIN_URL.'rabbits/wean/'.$rabbit['product_id']?>">
					<div class="input-box">
						<label>Number of Bucks</label>
						<input type="number" name="no_of_bucks"/>
						<input type="submit" value="Wean"/>	
					</div>
				</form>
<!--	<a href="<?php echo ADMIN_URL.'rabbits/wean/'.$rabbit['product_id']?>">Yes</a>
	<a href="#">No</a>-->
<?php elseif(!isset($rabbit['rabbit_latest_weaning_date']) or !$rabbit['rabbit_latest_weaning_date'] or $wean_diff < 21):?>
	<div class="status"><h3>We have to wait for <?php echo (21 - $wean_diff)?> to <?php echo (28 - $wean_diff)?> days for weaning</h3></div>
	<?php $litters = getModel('litter')->getWeaningCollection($rabbit['product_id']);?>
	<ul>
		<?php foreach($litters as $litter):?>
			<li><p><?php echo 'Litter '.$litter['litter_id'];?></p>
			<form method="post" action ="<?php echo ADMIN_URL.'rabbits/updateLitterWeight'?>">
			<input type="hidden" name="litter_id" value="<?php echo $litter['litter_id']?>"/>
			<div class="input-box">
				<label>Weight of Litter</label>
				<input type="text" name="weight" value="<?php echo ($litter['litter_weight'] == 'NULL')?null:$litter['litter_weight']?>"/>
				<input type="submit" value="Save"/>
			</div>
			</form>
			<div class="litterdeath">
				Is Litter Dead:<input type="checkbox" class="littercheck"> 	 <?php $litter_id=	$litter['litter_id']; ?>
				<a class='litterajax' href="<?php echo ADMIN_URL.'rabbits/deathlitterActions/'.$litter_id?>" style="display:none">Actions</a>
			</div>

			</li>

		<?php endforeach;?>
	</ul>
<?php elseif(!isset($rabbit['rabbit_latest_weaning_date']) or !$rabbit['rabbit_latest_weaning_date'] or $wean_diff > 28):?>
	<div class="status"><h3>Weaning Date exceeded. Rabbit will be available for mating</h3></div>
	<?php getModel('rabbit')->resetDates($rabbit_id);?>
<?php endif;?>
<?php else:?>
	<?php $rabbits = getModel('litter')->getSameParentRabbits($rabbit['parent_doe_id'], $rabbit['parent_buck_id']);?>

	<p>Parent Doe:<?php echo $rabbit['parent_doe_id'];?></p>
	<p>Parent Buck:<?php echo $rabbit['parent_buck_id'];?></p>
	<?php $wean_date = new DateTime($rabbit['rabbit_latest_weaning_date']);?>
	<?php $cull_diff = $today->diff($wean_date)->format("%a");?>
	<?php if($cull_diff <= 0):?>
		<p>We have to wait for <?php echo (60 - $cull_diff)?> days to begin culling.</p>
		<ul>
			<?php if($rabbits):?>
				<?php foreach($rabbits as $r_id):?>
					<?php $ra = getModel('rabbit')->load($r_id['rabbit_id']);?>

					<li>
						<p><?php echo $ra['product_name'];?></p>
					</li>
				<?php endforeach;?>
			<?php endif;?>
		</ul>
	<?php else:?>

		<p>Time for culling</p>
		<ul>
			<?php foreach($rabbits as $r_id):?>
				<?php $ra = getModel('rabbit')->load($r_id['rabbit_id']);?>		
				<?php $wean_date1 = new DateTime($ra['rabbit_latest_weaning_date']);?>
				<?php $cull_diff1= $today->diff($wean_date1)->format('%a');?>	
				<li>
					<p><?php echo $ra['product_name'];?>
					<?php if($cull_diff1 >= 60):?>
						<div class="options">
							<form method = "post" action="<?php echo ADMIN_URL.'rabbits/cull/'.$ra['product_id']?>">
								<input type="hidden" name="rabbit_id" value="<?php echo $ra['product_id']?>"/>
								<select name="group">
									<option value="19">Parent to be</option>
									<option value="21">Product to be</option>
								</select>

								<input type="submit" value="Cull"/>
							</form>
						</div>
					<?php endif;?>
					</li>
				<?php endforeach;?>
			</ul>
		<?php endif;?>
	<?php endif;?>
<?php elseif($rabbit['rabbit_gender'] == 'Male'):?>
	<?php if(!isset($rabbit['is_litter']) or strtolower($rabbit['is_litter']) == 'no'):?>
		<?php if(!isset($rabbit['rabbit_latest_mate_date']) or !$rabbit['rabbit_latest_mate_date']):?>
			<div class="status"><h3>Available for Mating</h3></div>
		<?php else:?>
			<div class="status"><h3>Rabbit was Mated <?php echo $mate_diff?> days ago</h3></div>
		<?php endif;?>
	<?php else:?>
		<?php $rabbits = getModel('litter')->getSameParentRabbits($rabbit['parent_doe_id'], $rabbit['parent_buck_id']);?>

		<p>Parent Doe:<?php echo $rabbit['parent_doe_id'];?></p>
		<p>Parent Buck:<?php echo $rabbit['parent_buck_id'];?></p>
		<?php $wean_date = new DateTime($rabbit['rabbit_latest_weaning_date']);?>
		<?php $cull_diff = $today->diff($wean_date)->format("%a");?>
		<?php if($cull_diff <= 60):?>
			<div class="status"><h3>We have to wait for <?php echo (60 - $cull_diff)?> days to begin culling.</h3></div>
			<?php //var_dump($rabbits);die;?>
			<ul>
				<?php foreach($rabbits as $r_id):?>
					<?php $ra = getModel('rabbit')->load($r_id['rabbit_id']);?>

					<li>
						<p><?php echo $ra['product_name'];?></p>
					</li>
				<?php endforeach;?>

			</ul>
		<?php else:?>
			<p>Time for culling</p>
			<ul>
				<?php if($rabbits):?>
					<?php foreach($rabbits as $r_id):?>
						<?php $ra = getModel('rabbit')->load($r_id['rabbit_id']);?>			
						<?php $wean_date1 = new DateTime($ra['rabbit_latest_weaning_date']);?>
						<?php $cull_diff1= $today->diff($wean_date1)->format('%a');?>	
						<li>
							<p><?php echo $ra['product_name'];?>
							<?php if($cull_diff1 >= 60):?>
								<div class="options">
									<form method = "post" action="<?php echo ADMIN_URL.'rabbits/cull/'.$ra['product_id']?>">
										<input type="hidden" name="rabbit_id" value="<?php echo $ra['product_id']?>"/>
										<select name="group">
											<option value="19">Parent to be</option>
											<option value="21">Product to be</option>
										</select>

										<input type="submit" value="Cull"/>
									</form>
								</div>
							<?php endif;?>
							</li>
						<?php endforeach;?>
					<?php endif;?>
				</ul>
			<?php endif;?>


		<?php endif;?>
	<?php else:?>
		<div class="status"><h3>Litters were born on <?php echo $rabbit['rabbit_dob']?></h3></div>
		<?php $litters = getModel('litter')->getCollection($rabbit['parent_id']);?>
		<?php echo $litters[0]['litters_weaning_date'];?>
		<?php $wean_date = new DateTime($litters[0]['litters_weaning_date']);?>
		<?php $cull_diff = $today->diff($wean_date)->format("%a");?>
		<?php if($cull_diff <= 0):?>
			<div class="status"><h3>We have to wait for <?php echo (60 - $cull_diff)?> days to begin culling.</h3></div>
			<ul>
				<?php foreach($litters as $litter):?>
					<li><?php echo 'Litter '.$litter['litter_id'];?></li>
				<?php endforeach;?>
			</ul>
		<?php else:?>
			<p>Time for culling</p>
			<ul>
				<?php foreach($litters as $litter):?>

					<li><?php echo 'Litter '.$litter['litter_id'];?><a href="#">Cull</a></li>
					<div class="options">
						<form method = "post" action="<?php echo ADMIN_URL.'rabbits/cull/'.$litter['litter_id']?>">
							<input type="hidden" name="rabbit_id" value="<?php echo $rabbit['product_id']?>"/>
							<select name="gender">
								<option value="11">Male</option>
								<option value="12">Female</option>
							</select>

							<select name="group">
								<option value="19">Parent to be</option>
								<option value="21">Product to be</option>
							</select>

							<input type="submit" value="Cull"/>
						</form>
					</div>
				<?php endforeach;?>
			</ul>
		<?php endif;?>
	<?php endif;?>
<?php endif;?>
<div class="death">
	<p>Is rabbit Dead:</p><input type="checkbox"/>
</div>
<a class='ajax' href="<?php echo ADMIN_URL.'rabbits/deathActions/'.$rabbit_id?>" style="display:none">Actions</a>
<a class='still_birth_ajax' href="<?php echo ADMIN_URL.'rabbits/stillbirth/'.$rabbit_id?>" style="display:none">Actions</a>
<script type="text/javascript">
	$(document).ready(function(){
		$('.ajax').colorbox({width:"50%", height:"auto"});
		$('.still_birth_ajax').colorbox({width:"50%", height:"auto"});
		$('.death').click(function(){
			$(this).parent().parent().find('a.ajax').trigger("click");
		});

		$('.still_birth').click(function(){
			console.log($(this).parent().find('a.still_birth_ajax'));
			$(this).parent().find('a.still_birth_ajax').trigger('click');
		});
	});

	$('.littercheck').click(function(){
		if (this.checked) {     	
			$('.litterajax').colorbox({width:"50%"});
			$(this).parent().find('a.litterajax').trigger("click");
		}
	});
</script>
</div><!--End rabbit-popup-->
<!--End popup cover-->
