<div class="rabbits">
	<?php foreach($families as $family):?>
		<h3>Family <?php echo $family;?></h3>
		<?php $rabbits = getModel('rabbit')->getFamilyRabbits($family);?>
		<ul>
		<form method="post" action="<?php echo ADMIN_URL.'rabbits/performMating'?>" class="form_<?php echo $family;?>">
		<?php foreach($rabbits as $rabbit_id):?>
			<?php $rabbit = getModel('rabbit')->load($rabbit_id);?>
			<?php $dob = new DateTime($rabbit['rabbit_dob']);?>
			<?php $mate_date = new DateTime($rabbit['rabbit_latest_mate_date']);?>
			<?php $today = new DateTime(date('Y-m-d'));?>
			<?php $diff = $today->diff($dob)->format("%a");?>
			<?php $mate_diff = $today->diff($mate_date)->format("%a");?>
			<li>
			<div class="rabbit <?php echo $status_class?>">
			<p><?php echo $rabbit['product_name'];?></p>
			<p><?php echo $rabbit['rabbit_gender'];?></p>
			<input type="radio" name="family_<?php echo $rabbit['rabbit_gender']?>"value="<?php echo $rabbit['product_id']?>" onchange="checkToMate(this,<?php echo $family?>)"/>
			<a href="javascript:void(0)" class="select" onclick="selectRabbit(this,<?php echo $family?>)">Select</a>
			
			</div>
			<a class='ajax' href="<?php echo ADMIN_URL.'rabbits/listActions/'.$rabbit_id?>" style="display:none">Actions</a>
			</li>
		<?php endforeach;?>
			<input type="submit" value="Mate" disabled class="submit"/>
			</form>
			<script type="text/javascript">
			$(document).ready(function(){
				$('.ajax').colorbox({width:"50%"});
				$('.rabbit').click(function(){
					$(this).parent().find('a.ajax').trigger("click");
				});
			});
			function checkToMate(radio, family_id)
			{
				var parent = $(radio).parent().parent().parent();
				if($(parent).find('input[name=family_Male]').is(':checked') && $(parent).find('input[name=family_Female]').is(':checked'))	
				{
					$(parent).find('input.submit').removeAttr('disabled');
				}
			}

			function selectRabbit(link,family_id)
			{
				var parent = $(link).parent().find('input[type=radio]');
				if($(parent).attr('checked') == true)
					$(parent).attr('checked',false);
				else
				{
					$(parent).prop('checked',true);
					checkToMate(parent, family_id);
				}
			}
			</script>
		</ul>
	<?php endforeach;?>
</div>