<div class="row">
<div class="col-lg-5 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
<div class="well">
<form method="post" action="">
<fieldset>
	<div class="row">
		<div class="col-lg-12">
		<label for="supplier_name">Supplier Name</label>
		<input type="text" name="supplier_name" class="form-control required"/>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-12">
		<label for="supplier_address">Supplier Address</label>
		<input type="text" class="form-control required" name="supplier_address"/>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-12">
		<label for="supplier_email">Supplier Email</label>
		<input type="text" class="form-control required" name="supplier_email"/>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-12">
		<label for="supplier_phone">Supplier Phone</label>
		<input type="text" class="form-control required" name="supplier_phone"/>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-12 text-right">
		<input type="submit" class="btn btn-primary" value="Save Supplier"/>
		</div>
	</div>
</fieldset>
</form>
</div>
</div>
</div>